### PR TITLE
Release as `scylla-cpp-driver`

### PR DESCRIPTION
**Pull request by jul-stas**
These changes are mostly about naming, updating licenses and pointing to our websites.
Tested on Centos 7 and Ubuntu 18.04.

### CODE REVIEW

**Review by penberg — APPROVED** [review]
Looks good to me. Let's see if we can also get @syuu1228 to review this.

**Comment by sitano** [comment]
@penberg on Debian it is missing zlib dependency

**Comment by sitano** [comment]
@jul-stas overall I built it well on Debian docker and it installed fine. So I guess its overall well. There are warns from the packaging linter that can be fixed. And also I would suggest checking the thing with `pbuilder-dist`. I am sorry I can't invest more into that.

**Comment by jul-stas** [comment]
> @jul-stas on Debian it is missing zlib-dev dependency
Now I see: zlib dependency can be toggled off in cmake. So it can stay as it is now.

**Pull request merged**
