### PR TITLE
docs: added sphinx

### PR DESCRIPTION
**Pull request by dgarcia360**
Related issue https://github.com/scylladb/cpp-driver/issues/15

Adds Sphinx and [sphinx-scylla-theme](https://sphinx-theme.scylladb.com/) to the cpp-driver repository.

# How to test this PR

Run ``make preview`` under the docs directory and open http://localhost:5500/ to check if the site is rendering.

### CODE REVIEW

**Comment by jul-stas** [comment]
I'm new to this, but `make preview` built and ran nicely, so LGTM.

**Comment by jul-stas** [comment]
@dgarcia360 do you know somebody who can review it more thoroughly?

**Comment by dgarcia360** [comment]
@lauranovich @tzach Please review when you have some time.

**Comment by lauranovich** [comment]
I was not able to run make preview without errors
No dependencies to install or update
cd .. && doxygen Doxyfile.in
/bin/sh: doxygen: command not found
make: *** [Makefile:27: setup] Error 127

I do not have doxygen installed

**Comment by dgarcia360** [comment]
Install [doxygen](https://github.com/scylladb/cpp-driver/blob/d9881047d9eda825ff59c592e2ab6111c2fc9857/README-dev.rst#building-the-docs) (Fedora) with the command ``sudo dnf install doxygen``

**Comment by lauranovich** [comment]
OK it runs now without error. 
the theme looks nice
we still need to handle the content and the links.
we should do this in a separate PR

**Review by lauranovich — APPROVED** [review]
theme looks good
all relevant parts are working nicely
the content should have the links changed in a separate PR.

**Pull request merged**
