### PR TITLE
Replace upstream links

### LINKED ISSUE #24: Replace links to scylladb.com
Replace links pointing to the upstream repo to scylladb.com

(Assigned to myself)

### PR DESCRIPTION
**Pull request by dgarcia360**
Closes #24 

Replaces automatically the links all the links with the form http://datastax.github.io/cpp-driver/* and http://docs.datastax.com/en/developer/cpp-driver/* to https://cpp-driver.docs.scylladb.com/*.

## How to test this PR

1. Enter the docs folder with ``cd docs``
2. Run ``make preview`` and open the documentation in your browser.
3. Under "Features", click on "Asynchronous API". 

tempsnip

As you can see in the screenshot, this is defined as a [Datastax link](https://github.com/scylladb/cpp-driver/compare/master...dgarcia360:replace-links?expand=1#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R199), but when you click on it should redirect
 you to https://cpp-driver.docs.scylladb.com/master/topics/#futures

### CODE REVIEW

**Comment by dgarcia360** [comment]
@lauranovich @tzach @jul-stas Please review

**Comment by dgarcia360** [comment]
@lauranovich @jul-stas Please review

**Comment by jul-stas** [comment]
Wow, is this a standard practice? Wouldn't it be safer to do it once, in the sources?

**Comment by dgarcia360** [comment]
@jul-stas This is the solution we ended choosing for the java-driver since one of the requirements was to edit fewer lines as possible from the source to avoid having merge conflicts when syncing with the upstream. 

Nevertheless, the java-driver is maintained unusually (custom commits are added on top of new upstream versions instead of integrating all changes in an integration branch like master). I agree with you that it will be cleaner if we replace the links directly in the sources.

@lauranovich @jul-stas Please let me know which option you prefer (replace links automatically vs. edit the links once manually).

**Comment by jul-stas** [comment]
OK, the value/effort coefficient convinces me. LGTM.

**Pull request merged**
